# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Arkan 👁️

on:
  push:
      branches: 
        - develop 
        - main
  pull_request:
      branches: 
        - develop
        - main 
        - "feat/**" 

env:
      NEXT_PUBLIC_API_KEY: ${{ secrets.API__KEY }}
      NEXT_PUBLIC_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      NEXT_PUBLIC_PROJECT_ID: ${{ secrets.PROJECT_ID }}
      NEXT_PUBLIC_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
      NEXT_PUBLIC_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_APP_ID: ${{ secrets.APP_ID }}
      NEXT_PUBLIC_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
